### ISSUE TITLE
implement requestLEScan

### ISSUE THREAD

**Issue by jimmywarting** [thegecko/webbluetooth#18]
https://chromestatus.com/feature/5346724402954240

**Comment by thegecko** [comment]
Is this the same as https://github.com/thegecko/webbluetooth/issues/2 ?

**Comment by jimmywarting** [comment]
hmm, yea it's

**Comment by pwespi** [comment]
Hi @thegecko, thanks for your great work on this project.

I realize this issue is quite old, so I hope it's OK if I continue the discussion here. I actually think `requestLEScan` is not the same as #2. `requestLEScan` is similar to `requestDevice`, but instead of returning a single device, it emits an event with every scan result. See [here](https://webbluetoothcg.github.io/web-bluetooth/scanning.html).

Would you consider adding this?
